spring:
  config:
    activate:
      on-profile: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:14fret
    username: sa
    password:
  h2:
    console:
      enabled: true
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
server:
  port: 8080
  forward-headers-strategy: NATIVE
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: 14fret
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360
