

name: Deploy to cloudtype
on:
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Connect
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          scope: cloudtype-ex
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: cloudtype-ex/react-abc
          yaml: |-
            name: vite-react
            app: web
            options:
              nodeversion: "16"
              docbase: /dist
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
